# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b10b44df789231b363f0f616a0645ca252c445561cced44cea574cf45778600c4dbb50dbd2c683874ffaf561bf71fb7d440907c2323e87afbcaf02581f3393d

test:
  secret_key_base: 2225f7b28fb3d8098e837ed1ba11b251aa551bbf1b3e948a9e0c97d9c38b01ca6b5d4278bb908796c3413aa94ea2dcd0c9e2be1ab12a2d14e1b5b226aefb3edf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
